# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    types: [opened, closed, reopened]
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: sudo apt-get install nodejs npm -y

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          npm install
          export PR_COUNT=$(curl -s https://api.github.com/repos/anveshkumarm/badges/pulls | jq '.[0].number')
          echo $PR_COUNT
          node createBadges.js
          echo Add other actions to build,
          echo test, and deploy your project.
      - name: move to dir # Move the generated files into output folder
        run: |
          mkdir -p output
          yes| cp -rf test.svg ./output/
      - name: Commit files # commit the output folder
        run: |
          git config --local user.email "test@github.com"
          git config --local user.name "GitHub Action test"
          git add ./output
          git commit -m "Add changes"
      - name: Push changes # push the output folder to your repo
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
